// AUTO-GENERATED by autogen.sh; DO NOT EDIT

#include "runtime.h"
void
runtime·GOMAXPROCS(int32 n, uint32, int32 ret)
{
#line 8 "runtime1.goc"

	ret = runtime·gomaxprocsfunc(n);
	FLUSH(&ret);
}
void
runtime·NumCPU(int32 ret)
{
#line 12 "runtime1.goc"

	ret = runtime·ncpu;
	FLUSH(&ret);
}
